### ISSUE TITLE
Error response from daemon: Pool overlaps with other one on this address space on new machine

### ISSUE THREAD

**Issue by rares1337** [ccarney16/pterodactyl-containers#104]
so i installed pterodactyl and whenever i try running the deamon it gives me this error
how do i fix

**Comment by ccarney16** [comment]
Refer to #100. I have explained in that the daemon creates its own network, however, you need to manually update the config to use a new CIDR/gateway for it to work properly. just use some IP address space like 172.30.0.0/16 and it should work.

**Comment by rares1337** [comment]
alright, been trying to work this out for 3 days, thanks

**Comment by alber70g** [comment]
> Refer to #100. I have explained in that the daemon creates its own network, however, you need to manually update the config to use a new CIDR/gateway for it to work properly. just use some IP address space like 172.30.0.0/16 and it should work.

What needs to be done in the config in order to achieve this? I'm running this on a server with multiple custom networks, and I've no clue what config item this corresponds to.

**Comment by Juganooo** [comment]
> > Refer to #100. I have explained in that the daemon creates its own network, however, you need to manually update the config to use a new CIDR/gateway for it to work properly. just use some IP address space like 172.30.0.0/16 and it should work.
> 
> What needs to be done in the config in order to achieve this? I'm running this on a server with multiple custom networks, and I've no clue what config item this corresponds to.

https://github.com/ccarney16/pterodactyl-containers/issues/100#issuecomment-2261321629
