### ISSUE TITLE
What is the yq binary and why are we supposed to trust it

### ISSUE THREAD

**Issue by psrcek** [ccarney16/pterodactyl-containers#105]
Looking through the code for this, there seems to be a random statically linked 64 bit ELF executable called `yq` with no documentation or source code that I could find.

What is this file and how are we supposed to know that it is trustworthy and that it won't do something like `rm -rf /*`.

**Comment by TekExplorer** [comment]
mikefarah/yq

though perhaps bin/deploy could download it instead of having it be included to begin with?

**Comment by psrcek** [comment]
Or just use the docker image as per documentation since docker is required anyway:

```bash
yq() {
  docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"
}
```

**Comment by TekExplorer** [comment]
that... is not a bad idea.

**Comment by ccarney16** [comment]
yq is to parse yaml files, I am looking to slowly move away from the deploy script and yq and move towards something like [ytt](https://carvel.dev/ytt/). I find it overall to be more configurable and adjustable compared to yq, and also allows injection of variables and templates. It can be used to just deploy the entire setup without writing a complex script.
