### ISSUE TITLE
How Do I get this to work with nginx-proxy

### ISSUE THREAD

**Issue by czadikem** [ccarney16/pterodactyl-containers#107]
Can you explain how I can get this to work with nginx proxy?  Since I can't get it two work and the daemon container gives me errors like `
FATAL: [Apr 25 04:12:04.029] failed to configure docker environment error=Error response from daemon: Pool overlaps with other one on this address space`  or  `Error response from Panel: HttpException: Access this this endpoint must include an Authorization header. (HTTP/401)`

**Comment by ccarney16** [comment]
I have never used nginx-proxy. Traefik/HAproxy has worked fine for me so far. The first error is regarding the issue of network generation, for that you need to manually configure the daemon in config/daemon/config.yml and change the ip addressing to something a docker network is not using.

**Comment by czadikem** [comment]
Ok thank you for your feedback.  I have got most of pterodactyl working the only issue is that I can't control pterodactyl with my domain name instead I have to use the server's ip.  Is there anything that you need so you can help me?

**Comment by ccarney16** [comment]
nginx-proxy has always felt more of a hack to me than an actual reverse proxy that can do things. Ive always recommended traefik for its configuration options and being an actual reverse proxy and load balancer that integrates well into many containerized environments.

**Comment by czadikem** [comment]
Ok I am willing to try to setup traefik.  What do you use to set up a traefik proxy with docker-compose

**Comment by czadikem** [comment]
Ok so traefik is setup and working how can I make it so I can use pterodactyl with it

**Comment by ccarney16** [comment]
You need to configure traefik to look at labels on docker, for example, I have a certbot container with the following labels:
```    labels:
    - traefik.enable=true
    - traefik.http.services.certbot.loadbalancer.server.port=80
    - traefik.http.routers.letsencrypt.rule=PathPrefix(`/.well-known/acme-challenge`)
    - traefik.http.routers.letsencrypt.priority=1000
```

DO NOT COPY/PASTE THIS CONFIGURATION, This will not work and only serves as an example. I would suggest looking into traefik's documentation at https://doc.traefik.io/traefik/

**Comment by czadikem** [comment]
Ok so I did get this to work with traefik, so thanks for your help.
