### ISSUE TITLE
nonexistent directory error

### ISSUE THREAD

**Issue by NaokiNXN** [ccarney16/pterodactyl-containers#110]
Had this all working okay till the most recent update and following this i now get the following error:

Seeded:  Database\Seeders\EggSeeder (198.12ms)
Database seeding completed successfully.
[setup] Warning: SSL Certificate was not specified or doesnt exist, using HTTP.
--- Starting Pterodactyl Panel: v1.4.2 ---
/entrypoint.sh: line 74: can't create /etc/nginx/conf.d/default.conf: nonexistent directory

It sometimes also appears as line 70 instead of 74.

Since i couldnt figure out a fix for it deleted everything and tried for a fresh install but this didnt work
either just kept getting the same error message.

Any ideas?

**Comment by ccarney16** [comment]
This is an issue in regards to changes to the base alpine image. I just committed a change to explicitly create the conf.d directory.

**Comment by NaokiNXN** [comment]
Brilliant all working now thanks :)
