### ISSUE TITLE
Having constant problems installing on unraid. Need guidance.

### ISSUE THREAD

**Issue by TheFantasticLoki** [ccarney16/pterodactyl-containers#112]
So I have been "attempting" to migrate my minecraft servers to unraid since running them in a hyper-v vm has it's drawbacks, but I am having CONSTANT issues with getting it to work properly. I installed the panel docker through the community apps section in unraid but ig that one doesn't include the daemon since my nodes refuse to connect to it. Plus I can't figure out where the daemon configs are located in the panel docker to manually make the configurations for the node.

Then I figured fuck it and decided to try installing through this githubs wiki quick start guide but now when I run docker compose I get error port 3306 already in use for the db connection closing compose.

I have been having quite a few issues using unraid so far but tbh it's just too good to not use at this point. But to get to the point I need some guidance on how to proceed from here as I would like to continue using the dockers for pterodactyl especially since I should be able to get around my isp blocking port 8080 using a reverse proxy and the port mappings in unraid.

**Comment by TheFantasticLoki** [comment]
if possible I would prefer to fix the community apps installed version as I can modify values through unraid gui.

**Comment by ccarney16** [comment]
I do not support unraid nor its community apps. The configuration for it is third party and vastly outdated the last time this was brought to my attention. My suggestion would be to see if you can run the panel and daemon within a virtual machine or find something to convert the docker-compose.yml file generated during deployment to something unraid sees and uses.

**Comment by thierrybla** [comment]
@TheFantasticLoki https://youtu.be/gESfcKDX804

**Comment by TheFantasticLoki** [comment]
Thank you @thierrybla I found that a while ago.

**Comment by TheFantasticLoki** [comment]
For those that find this thread make sure in your panel the daemon port is set to 443 and the actual daemon config.yml has the port as 8080 still otherwise you will have node connection issues

**Comment by fizzyfrys** [comment]
> @TheFantasticLoki https://youtu.be/gESfcKDX804

For anyone reading this in the future, if you have any other problems, I suggest joining IBRACORP's discord server: https://discord.gg/VWAG7rZ
