### ISSUE TITLE
bin/deploy failing when using Arm CPUs

### ISSUE THREAD

**Issue by 4P5** [ccarney16/pterodactyl-containers#126]
Getting the following error when running `bin/deploy` on a server using an Ampere Altra 80c processor.
```
Building Configuration...
./deploy: line 106: bin/yq: cannot execute binary file: Exec format error
./deploy: line 66: bin/yq: cannot execute binary file: Exec format error
```
I've tried multiple distributions of Linux, but the same errors happen for all of them.

**Comment by ccarney16** [comment]
yq is an x86 binary. I think I build the container images in ARM, but I do not offer official support. you can replace yq with an arm build as long as its v3
