### ISSUE TITLE
nothing produced in docker-compose.yml

### ISSUE THREAD

**Issue by DiffuseHyperion** [ccarney16/pterodactyl-containers#133]
after doing `./deploy --panel --daemon --certbot` in `/srv/app/pterodactyl/bin`, the docker-compose.yml produced in `/srv/app/pterodactyl` has no contents

**Comment by ccarney16** [comment]
I have performed a massive change with the deploy system. I no longer include yq and it needs to be downloaded onto the system. you can download it [here](https://github.com/mikefarah/yq/releases/tag/v4.23.1)

**Comment by DiffuseHyperion** [comment]
still nothing after updating to yq 4.24.2. i should have mentioned this earlier, but when building the compose file, it shows `Error: Value for env variable 'database_enabled' not provided in env()`, is there a .env file i need to edit somewhere?

**Comment by ccarney16** [comment]
Just updated the repo, made a mistake and forgot to change out a variable. should be good to pull and redeploy.

**Comment by DiffuseHyperion** [comment]
now it shows up as `Error: Value for env variable 'daemon_enabled' not provided in env()`, im assuming its another variable?

**Comment by ccarney16** [comment]
just pushed another update to the repo. this problem should be fixed now.

**Comment by DiffuseHyperion** [comment]
looks good, thanks for fixing
