### ISSUE TITLE
certbot unable to run

### ISSUE THREAD

**Issue by DiffuseHyperion** [ccarney16/pterodactyl-containers#134]
after doing `./deploy --panel --daemon --certbot`, doing `docker-compose run --rm --service-ports certbot certonly -d (my domain)`, it returns as:
```
Creating pterodactyl_certbot_run ... done
/var/www/html/public/ does not exist or is not a directory
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/tmp51rd_sv4/log or re-run Certbot with -v for more details.
```

**Comment by ccarney16** [comment]
The certbot service was modified during the layout overhaul of my compose projects, I forgot to add in the webroot volume, should be able to redeploy your instances with it now.
