### ISSUE TITLE
Schedule & Email workers not working

### ISSUE THREAD

**Issue by SerenModz21** [ccarney16/pterodactyl-containers#135]
Hello, I recently got into dockerizing a pterodactyl panel, using IBRACORP's example (https://docs.ibracorp.io/pterodactyl-docker-1/pterodactyl-docker/docker-compose) as a guide. However, I have noticed that neither the scheduler nor email workers work correctly.

Email worker:
I know this isn't working because when testing email settings, the test email gets sent out as expected. Where the issue comes into play is when inviting people to the panel or to a server. However, the emails of a user getting invited to the panel or being added to a server do not get sent. This is not the expected email worker behaviour. 

Scheduler worker:
When setting up schedules with multiple tasks, the first task in the schedule will run but the rest of them will get ignored. This is incorrect as the schedule should be running all tasks that have been added.

**Comment by ccarney16** [comment]
The email worker has been something ive been tackling for some time, however the best method to fix this would be to use or setup an SMTP server. I use mailgun personally and pterodactyl does have a driver for that. As with the scheduler, im not too sure whats going on with that. I would suggest bringing it up to the ibracorp guys to see if they are missing anything, as I dont run the queue worker and cron in the same container. The docker-compose deployment setup has been working fine.

**Comment by SerenModz21** [comment]
Thank you for your reply! I personally use SendGrid's SMTP Server for emails but for the scheduler worker, I will ask in the Ibracorp Discord servef when I get home.

**Comment by SerenModz21** [comment]
It seems as though it's just the `php artisan queue:work --queue=high,standard,low --sleep=3 --tries=3` ([more info](https://pterodactyl.io/panel/1.0/getting_started.html#create-queue-worker)) command that is being executed in the background because if I exec into the docker container and run it myself, emails and schedules start working.

After a bit of research, the best way to do this would be to use a process manager, such as supervisord. An example can be found on the docker documentation (https://docs.docker.com/config/containers/multi-service_container/) and in the official Dockerfile (https://github.com/pterodactyl/panel/blob/develop/Dockerfile).

The queue worker process can then be found in the supervisord.conf file:
https://github.com/pterodactyl/panel/blob/develop/.github/docker/supervisord.conf#L27-L31

**Comment by ccarney16** [comment]
I have avoided an init process because of how unreliable they can be and how much bloat they cause. My recommendation for my deployment has been to run cron/worker as independent containers, and have included start commands to execute them (p:cron, p:worker). If you want the full reference, you can always look at my compose configuration and get an idea.

**Comment by SerenModz21** [comment]
Oh, ok. I will give your compose configuration a try. Thank you for your time!
