### ISSUE TITLE
Update release versions

### ISSUE THREAD

**Issue by SGTGunner** [ccarney16/pterodactyl-containers#137]
@ccarney16,
Both Wings and Ptero have been updated. Please update the manifest file.

Thanks.

**Comment by TekExplorer** [comment]
It's automated by workflow

**Comment by dbunduc** [comment]
this brakes the panel, the official pterodactyl panel 1.8.0 made some breaking changes.

**Comment by TekExplorer** [comment]
> this brakes the panel, the official pterodactyl panel 1.8.0 made some breaking changes. It needs redis.

it seems to work fine for me

**Comment by SGTGunner** [comment]
okay, thanks. I did not know it was on an automated process for updating.
