### ISSUE TITLE
/bin/artisan error

### ISSUE THREAD

**Issue by DiffuseHyperion** [ccarney16/pterodactyl-containers#144]
Whenever I run `./bin/artisan p:user:make` in the project's root directory, I get the following error:
```
-e  Warning! This command is intended for interactive sessions only. Please use docker compose directly for use in scripts.
./artisan: 13: [[: not found
Docker Compose service "panel" does not exist! Exiting...
```
Running `docker compose config --services` outputs this:
```
certbot
cron
daemon
mariadb
redis
panel
worker
```
Showing that panel was indeed running.
I found that changing the script to a bash script fixes this, but i'm unsure if you want to keep it as a sh script for compatibility.

**Comment by DiffuseHyperion** [comment]
Now that I think about it, /bin/certbot would also be affected by this, since they are practically the same script.

**Comment by ccarney16** [comment]
Feel free to use docker-compose exec panel php artisan p:user:make. Those scripts are mainly aliases than writing out the full command. Ill investigate that since it seems to affect some distributions.

**Comment by luiz-otavio** [comment]
Did you try to get in `bin/` directory and then execute this command? If it doesn't work, try to use `bash bin/artisan p:user:make`, might it will work as should it need.

**Comment by Vapestorm** [comment]
Assuming that you're already running a container with these services. Try to use:
`docker exec -it <your_container_panel_id> php artisan p:user:make`.

Then, you will get the input for create a new user.
![image](https://user-images.githubusercontent.com/67751668/199626281-72af5f28-ee92-4494-88a1-90fcefa55199.png)

**Comment by ccarney16** [comment]
Updated scripts to use bash instead of sh, this should fix the problem.
