### ISSUE TITLE
Build for Panel Image v1.11.4 failed

### ISSUE THREAD

**Issue by galexrt** [ccarney16/pterodactyl-containers#149]
It seems that the build for 1.11.4 has failed: https://github.com/ccarney16/pterodactyl-containers/actions/runs/4129631596/jobs/7135445598

Any way to get it fixed? Maybe a CI re-run is enough?

**Comment by ccarney16** [comment]
There seems to be an issue with the github runner which is preventing yarn from getting the required dependencies for the panel. Building the project locally is working fine. I do notice that current actions do need to be updated at some point.

**Comment by galexrt** [comment]
@ccarney16 Anyway to get a 1.11.4 tag pushed to your Docker Hub besides building it ourselves?

**Comment by ccarney16** [comment]
I am not sure what you are referring to, Panel v1.11.4 does not exist, nor is a release on the official github repo.

**Comment by galexrt** [comment]
@ccarney16 Oh, I confused the wings release with the panel's releases. Feel free to close the issue.
