### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by liyanagelahiru** [ccarney16/pterodactyl-containers#158]
can you publish arm64 image ?

**Comment by ccarney16** [comment]
Hey, at the moment I am not publishing arm64 images. I had arm images built in the past however they had issues during build which caused the CI/CD to freeze and halt building. It is something I would be willing to look into the future but for right now I would suggest using the build template provided with this project.

**Comment by liyanagelahiru** [comment]
can you give Deckerfille then i can build my self

**Comment by liyanagelahiru** [comment]
![image](https://github.com/ccarney16/pterodactyl-containers/assets/153709260/0d49851b-237a-40a6-90cd-1ef41965c411)
how fix this my db creads are correct
