### ISSUE TITLE
2FA not working during login

### ISSUE THREAD

**Issue by triptronics** [ccarney16/pterodactyl-containers#28]
Hello guys,

I have setup a admin account with 2FA authentication. The token is verified successfully when setting up but when I log out and log back in with the 2FA code, it says that it is incorrect. I checked the clocks for the servers and device. Also worth mentioning the panel accepted the token when setting up so I know that part is working properly. I used a generic password and username as well so I know these are inputted properly. I can even use the php artisan:disable2fa command and then log back in and enable it again and without logging out, disable it and it disables fine. The only thing that's not working is the main purpose which is during log-on ;-;

**Comment by ccarney16** [comment]
Would you be able to provide logs from pterodactyl, they should be /data/storage/logs/laravel-<date>.log?

**Comment by triptronics** [comment]
Hi, yes I can. 
[error_log.txt](https://github.com/ccarney16/pterodactyl-docker/files/4006511/error_log.txt)

Also a note, the servers time is set to a different timezone than that of where the actual server is located. Could this be the issue? The strange thing though... when you enable 2FA it says the code is good or otherwise it wouldn't enable it. It's only on the login screen where the credentials keep failing... Thanks again.

**Comment by sevospl** [comment]
@triptronics @ccarney16 I have the same issue. Weirdly I can deactivate it back in the panel but trying to attempt a new session with 2FA is going to fail every time. I also tried with 2 apps -- Authy and Google Authenticator.

I changed manually the timezone to a proper one but it didn't seem to help.

**Comment by triptronics** [comment]
Can one of the owners verify this issue as well please? This is a inconvinent issue because if you enable 2FA then your account gets locked and you have to run a series of commands to get back into the account. If someone can please take a look into this, we would greatly appreciate it! Thank you! Otherwise, everything is working just fine.

**Comment by ccarney16** [comment]
In all my time deploying pterodactyl within this container, I have not run into this issue at all. and in regards to that error log that @triptronics posted, do you have any sort of email options setup?

**Comment by EdyTheCow** [comment]
> In all my time deploying pterodactyl within this container, I have not run into this issue at all. and in regards to that error log that @triptronics posted, do you have any sort of email options setup?

I am having the same issue but only when using Traefik reverse proxy. I noticed the 2FA issue isn't just pterodactyl related, I have the same exact issue on other software using 2FA when under Traefik reverse proxy. I haven't figured out the reason for why this is happening.

**Comment by ccarney16** [comment]
Closing, this is for an older version of the panel
