### ISSUE TITLE
first time setup error

### ISSUE THREAD

**Issue by Epyxx** [ccarney16/pterodactyl-containers#33]
Hello, i have set up a new docker instance with the latest version of pterodactyl-docker.
After starting i get error at the first time setup:

> Running first time setup...
> 
> Generating key...
> Application key set successfully.
> 
> Creating & seeding database...
> 
> In Connection.php line 664:
>                                                                                
>   SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
>   chema.tables where table_schema = panel and table_name = migrations)         
>                                                                                
> 
> In PDOConnection.php line 50:
>                                              
>   SQLSTATE[HY000] [2002] Connection refused  
>                                              
> 
> In PDOConnection.php line 46:
>                                              
>   SQLSTATE[HY000] [2002] Connection refused  
>                                              
> 
> Seeding: NestSeeder
> 
> In Connection.php line 664:
>                                                                                
>   SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `nests` where  
>    (`author` = support@pterodactyl.io))                                        
>                                                                                
> 
> In PDOConnection.php line 50:
>                                              
>   SQLSTATE[HY000] [2002] Connection refused  
>                                              
> 
> In PDOConnection.php line 46:
>                                              
>   SQLSTATE[HY000] [2002] Connection refused  
>                                              
> 
> Starting Pterodactyl v0.7.16 in 5 seconds...
> [Warning] Disabling HTTPS

After opening the web-interface i get an 500 Error.

**Comment by ccarney16** [comment]
Sometimes MariaDB does not start up right away. I suggest starting up mariadb before starting up the panel; you can do that by running `docker-compose up -d mysql` and wait 30 seconds

**Comment by Syntax3rror404** [comment]
If this not works i think you mariaDB first time init was wrong. You can check that by manual login to the mariadb container and try to open the database via the cli.

**Comment by ccarney16** [comment]
Closing, inactivity and older version of the panel
