### ISSUE TITLE
Install instructions unclear

### ISSUE THREAD

**Issue by 8549** [ccarney16/pterodactyl-containers#40]
Hi, when running for the first time the user create command `docker-compose run --rm panel php artisan p:user:make` i receive this error:
```
$ docker-compose run --rm panel php artisan p:user:make
Starting pterodactyl-docker_mysql_1 ... done
Starting pterodactyl-docker_cache_1 ... done

 Is this user an administrator? (yes/no) [no]:
 > yes

 Email Address:
 > [redacted]

 Username:
 > admin

 First Name:
 > a

 Last Name:
 > b

Passwords must be at least 8 characters in length and contain at least one capital letter and number.
If you would like to create an account with a random password emailed to the user, re-run this command (CTRL+C) and pass the `--no-password` flag.

 Password:
 >


In PDOConnection.php line 50:

  SQLSTATE[HY000] [1045] Access denied for user 'ptero'@'172.23.0.5' (using password: YES)


In PDOConnection.php line 46:

  SQLSTATE[HY000] [1045] Access denied for user 'ptero'@'172.23.0.5' (using password: YES)

```
Yes, i did wait a minute after starting the mysql container to start the panel container, and another minute after that before running the above command.
I'm on `Docker version 19.03.1, build 74b1e89` on Ubuntu 19.10. Thanks in advance.

**Comment by 8549** [comment]
Ok after cleaning everything up (including cloning again the repo) i could set it up without editing anything in the .env file. How should i edit it to change the default passwords? What do you mean by

> Copy the configuration to `/srv/daemon/config/core.json`.
? I don't understand which configuration.

**Comment by ccarney16** [comment]
Documentation has never been my thing (or in any cases, many admins bane of existence ). I plan on doing a full rewrite of my docker solution when the next major version of pterodactyl releases...
There are a lot of things I have learned from deploying my setup that should make it into the next major image release.

Now onto your question:  
> Copy the configuration to /srv/daemon/config/core.json.

This means to copy the daemon configuration created by the panel to that location on the host machine. You can also generate a token and have the daemon get the file using this command:
`docker-compose run --rm daemon <command-from-panel>`. I highly suggest referring to pterodactyl's documentation for some assistance, as the install guide relies on it.

**Comment by ccarney16** [comment]
Closing, inactivity and older version of the panel
