### ISSUE TITLE
Current version does not like being behind a reverse proxy?

### ISSUE THREAD

**Issue by dennorske** [ccarney16/pterodactyl-containers#53]
Hi! First of all, amazing work putting this together. It's really cool to see something that uses docker itself, to be placed inside docker as well - it allows for a very modular approach and you can put the different parts into clusters for load balancing and scaling when needed.

How do you recommend setting up the panel, when I want my existing apache2 set-up to handle the routing and SSL certificates?

1. I can't only forward port 80 to the webserver, as the login endpoint on pterodactyl will expect HTTP (and the 301 redirects will ruin the login flow with a "GET" request when i click "login").
2. Setting SSL active in the .env will make the panel start looking for local certs (handled in the docker container) and hence, also open up for SSL on the backend (using port 443).
3. The Daemon can still be how it is, because it is exposed to a different port, and can read the same directory for the certificates as apache uses for verification.
4.  Why didn't you design it with a reverse proxy in mind for the panel itself? As it is now, it is required to bind the entire setup to the main ports, but realistically there are already applications listening on port 80 and 443.

**Summary:**
Setting up an apache config in front of this then requires both port 80 and port 443 to be used, which I can't make happen with the current setup. 

I'd be super happy to get some insight on how to solve this

**Comment by ccarney16** [comment]
This project has been setup in mind with a reverse proxy, however the default compose file does not expect any sort of reverse proxy setup. I haven't personally worked with apache2 for my setup, but it should act the same as any other reverse proxy. I recommend that you stick with one protocol for the backend communication, http or https. Apache2 should be the one to automatically change protocols out, as sending both http and https traffic to the backend service may cause unintended results.

Beyond that, I recommend using nginx/haproxy/traefik for all load balancing/reverse proxy needs as those can properly handle the traffic and routing. I have tested all of those solutions on this setup and those work fine.

**Comment by ccarney16** [comment]
Closing: inactivity and older version of the panel
