### ISSUE TITLE
Error while attempting to fetch list of eggs from the panel.

### ISSUE THREAD

**Issue by merid14** [ccarney16/pterodactyl-containers#57]
Hi, trying to get the daemon setup. I'm running this behind traefik. I've added a node in the portal and configured the core.json file. 
However, i get a network error. shown below.

```daemon_1         | 04:09:08.508Z  INFO wings: Checking container networking environment...
daemon_1         | 04:09:08.515Z  INFO wings: Found network interface for daemon: pterodactyl_nw
daemon_1         | 04:09:08.516Z  INFO wings: Ensuring correct network interface for containers...
daemon_1         | 04:09:08.526Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
daemon_1         | 04:09:08.528Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
daemon_1         | 04:09:08.567Z FATAL wings: A fatal error caused the daemon to abort the startup.
daemon_1         |     Error: Error while attempting to fetch list of Eggs from the panel.
daemon_1         |         at Request [as _callback] (/srv/daemon/src/controllers/service.js:95:31)
daemon_1         |         at Request.self.callback (/srv/daemon/node_modules/request/request.js:185:22)
daemon_1         |         at emitTwo (events.js:126:13)
daemon_1         |         at Request.emit (events.js:214:7)
daemon_1         |         at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1157:10)
daemon_1         |         at emitOne (events.js:116:13)
daemon_1         |         at Request.emit (events.js:211:7)
daemon_1         |         at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1079:12)
daemon_1         |         at Object.onceWrapper (events.js:313:30)
daemon_1         |         at emitNone (events.js:111:20)
daemon_1         |     --
daemon_1         |     additional: {
daemon_1         |       "responseCode": 401,
daemon_1         |       "requestURL": "http://mysite.com/api/remote/eggs"
daemon_1         |     }
daemon_1         | 04:09:08.568Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
```
 Reading the documentation is a bit cryptic. `recommended to change the network parameters` i'm not sure what you mean by that. could you clarify?

```Copy the configuration to /srv/daemon/config/core.json. It is recommended to change the network parameters or the daemon may crash (If you have not used pterodactyl before, it will attempt to use the 172.18.0.0/16 block). In json notation, you should modify docker.network.interfaces.v4.subnet and docker.network.interfaces.v4.gateway.```

**Comment by ccarney16** [comment]
The Daemon is getting HTTP error 401, which means unauthorized access by the panel or traefik. I would recommend trying redeploying your daemon within the panel.

Also, the documentation is in dire need of updates. when v1 launches, I do plan on rewriting the installation page to clarify what is going on. What I mean with the networking is that the daemon will crash if pterodactyl_nw does not exist AND the default ip address range has been taken (172.18.0.0/26). To fix this issue without describing the issue in further detail, just run `docker network create pterodactyl_nw`.

**Comment by merid14** [comment]
I feel like there may be more that i'm missing as far as configuration in the panel. As you noted there is a 401 error and it's trying to access the api. I never setup an api key. Is that necessary?

Steps I initially took were to setup a node. Which i just pointed at the panel ip.  then access the configuration file. Copy that config into the panel at `/srv/daemon/config/core.json` Then start the daemon. Is there something in here I missed? Is this what you mean by redeploy the daemon within the panel?

That does make sense in regards to the network config. However, the pterodactyl_nw network was already created and with that Ip range. 

Thanks for your assistance on this.

**Comment by ccarney16** [comment]
API keys are not required for the daemon, it has its own key setup that is separate from application API keys. I would suggest to reset the daemon master key and recopy the daemon config. As you have stated that you are using traefik, I would recommend looking at the proxy and/or setting the `TRUSTED_PROXIES` variable in the pterodactyl panel env file to see if setting that will help.

**Comment by ccarney16** [comment]
Closing: inactivity and older version of the panel
