### ISSUE TITLE
TODO: Make better documentation

### ISSUE THREAD

**Issue by ccarney16** [ccarney16/pterodactyl-containers#63]
There clearly needs to be better documentation for this project. While I am not horrible in writing docs, I am clearly not the best at doing so. If anyone wants to assist in helping me write better documentation, feel free to write a reply here or message me on Discord. My username is Zyphys#2739.

Documentation will be written for the new branch `beta/v1.0.0`, as I do not have plans to continue maintaining panel version `v0.7.x`. While my priority is documentation for docker-compose, tools and other documentation are welcome.

**Comment by thierrybla** [comment]
I really love what you do thanks for that !

However I find it really hard to understand on how I would use this + a separate reverse proxy container (for example letsencrypt contrainer from linuxserver.io) could that be added to the explanation / documentation ?

Thanks in advance!

**Comment by ccarney16** [comment]
Thank you for your input! 

Yeah, my aim is to have this project seamlessly mix into your setup. However I do not plan on documenting everything under the sun, just the project itself and some popular setups. I will accept feedback in regards to nginx-proxy and traefik, but not for random "X" container. I do plan on providing better documentation so users can understand more on how the images function and provide answers to tweaking such as using an external directory for certificates.

**Comment by TekExplorer** [comment]
[EdyTheCow](https://github.com/EdyTheCow/pterodactyl-docker) has a rather nice guide for using it with traefik and cloudflare, though its not perfect. i plan on making one myself at some point as well.
