### ISSUE TITLE
invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by inenting** [ccarney16/pterodactyl-containers#67]
I am using docker on unraid and I managed to install both dockers without a problem, however when I try to create a server I get the following error on the daemon:

`FATAL wings: A fatal error was encountered while attempting to create a server.`

`Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist: /srv/daemon-data/ba197a0d-d822-4276-b7fb-34684d293658`

`at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:287:7)
at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:256:5)
at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:232:14)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
at process._tickDomainCallback (internal/process/next_tick.js:219:9)`

I have noticed that the Packs Path and Data Patch are variables instead of path, I have tried replacing them with paths but that didn't help.

I have seen a similar issue here but that was for ovh but i'm using my own server. The path does exist but it doesn't make the folder so it might be a permission issue but it didn't work out of the box either and I also tried changing the path to a share on my array but no dice.

**Comment by ccarney16** [comment]
Which branch are you using? master was recently changed to v1 rc versions, however I did not make them the latest container-wise.

**Comment by inenting** [comment]
I'm using ccarney16/pterodactyl-daemon:latest and ccarney16/pterodactyl-panel:latest , which is the v0.7.18 panel version

**Comment by ccarney16** [comment]
Yes, however are you using the git branch where it has a script called create-project in bin/?

**Comment by inenting** [comment]
I'm sorry, i'm not quite sure, everything was installed automatically from : 

https://hub.docker.com/r/ccarney16/pterodactyl-daemon/tags
https://hub.docker.com/r/ccarney16/pterodactyl-panel/tags

With the images called latest

I tried looking in /bin in the docker images with shell but can't find a create-project file

**Comment by ccarney16** [comment]
are you using docker-compose for the project?

**Comment by inenting** [comment]
No, I am using something called Community Applications, which is like an app store and it installs docker images for me. I don't have experience manually installing via console and haven't done it on my unraid installation.

**Comment by ccarney16** [comment]
I do not support with this method of installation and have not worked with unraid. However I do suggest looking at both [compose](https://github.com/ccarney16/pterodactyl-containers/blob/v0.7/docker-compose.yml) and [extras](https://github.com/ccarney16/pterodactyl-containers/blob/v0.7/docker-compose.extra.yml) files to see how to set the container up correctly. The daemon requires volume mounts to be directories, not managed volumes via docker.

**Comment by inenting** [comment]
The volumes are mounted and accessible from the docker. I can create folders/files from inside the docker. But even when I create a server it creates the folder : 

17:40:20.093Z WARN wings: Container was not found. Attempting to recreate it. (server=859c2606-6a40-4065-b753-6e2ebe3c7dd5)

But then I get the error: 
Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist: /srv/daemon-data/859c2606-6a40-4065-b753-6e2ebe3c7dd5

And then it deletes the folder again:
17:40:35.859Z INFO wings: Server deleted. (server=859c2606-6a40-4065-b753-6e2ebe3c7dd5)

I connected the /srv/daemon-data as a smb share and I can see the folder getting created and deleted

**Comment by ccarney16** [comment]
I dont know what is going on with that then. I have never seen a setup like this before. Also the daemon does not randomly delete folders. Can I see your container config for both the panel/daemon?

**Comment by inenting** [comment]
Is the container config a json file?

**Comment by inenting** [comment]
I found a solution on the forum thread of the guy that updates the repo, it has to do with pterodactyl not liking it when you dont map the volume 1:1 , see link below:

https://forums.unraid.net/topic/89502-support-a75g-repo/?do=findComment&comment=874285

Looks like this can only be fixed by the pterodactyl team, thank you so much for your help and time!
