### ISSUE TITLE
Data integrity exception while performing database write op

### ISSUE THREAD

**Issue by alextwothousand** [ccarney16/pterodactyl-containers#70]
I'm getting 
```
  Data integrity exception encountered while performing database write operation. {"uuid":["The uuid field is required."],"email":["The email field is required."],"username":["The username fi  
  eld is required."],"name_first":["The name first field is required."],"name_last":["The name last field is required."]}
```
whenever I run `docker-compose exec panel php artisan p:user:make`. I get the error, but I don't think this is an issue with my set up as I have basically followed the tutorial in the wiki. What can I do to fix this?

**Comment by ccarney16** [comment]
What version of the panel are you running? I haven't encountered that error on either v0.7 or v1. From what it looks like, its attempting to read args from cli rather than interactive mode.

**Comment by devlexanderxyz** [comment]
Latest version.

**Comment by ccarney16** [comment]
the latest version on docker hub is v0.7, however, the master branch uses v1 (which has not pushed since rc3 and is not tagged as the latest). When it comes to deploy, I recommend using --build to enable build options, as that is currently the only option for master at the moment.

**Comment by devlexanderxyz** [comment]
I just followed the instructions on your wiki. How would I modify those
instructions to do what you’ve suggested?

**Comment by ccarney16** [comment]
to enable build options, you use `bin/deploy --build` then use `docker-compose up -d panel daemon worker cron` to start the building process for the containers. I do recommend starting from scratch as v0.7 and v1 databases are different and have yet to go through a good upgrade path. You can clear out the panel/database config in data.

**Comment by devlexanderxyz** [comment]
Thank you! I will try this and let you know how it goes

**Comment by devlexanderxyz** [comment]
Hi there
I'm now getting php_network_getaddresses: getaddrinfo failed: Name does not resolve
Is there anything specific I must enable/disable? Thank you

**Comment by ccarney16** [comment]
can I get a full log output on that?
