### ISSUE TITLE
Error when trying to create a server

### ISSUE THREAD

**Issue by EdyTheCow** [ccarney16/pterodactyl-containers#74]
I am getting this error when trying to create a server on the panel:

`failed to run install process for server error=failed to pull updated installation container image for server: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39 `

I am using docker images daemon v1.0.0 and panel v1.0.0 from docker hub. It does say panel version is "canary" in the dashboard. Not sure if it's supposed to say that or if image was built from dev version of the panel.

**Comment by ccarney16** [comment]
Pull v1 again, I fixed that issue in regards to pulling updates. I also suggest updating docker itself to see if that problem goes away.

**Comment by EdyTheCow** [comment]
Thanks, working as expected now.
