### ISSUE TITLE
Cron Container Running on Wrong Queue

### ISSUE THREAD

**Issue by ttpcodes** [ccarney16/pterodactyl-containers#78]
I was recently trying to debug why schedules wouldn't work on an installation of Pterodactyl that I set up with the containers in this repository, and stumbled upon this discrepancy in the configuration. It seems that the panel is configured to use Redis for the queue connection according to this line:
https://github.com/ccarney16/pterodactyl-containers/blob/290ea14654a4cfb2d2bcf4f25e67cafc5f63c521/manifest/config/env/panel.env#L35
However, the entrypoint script is configured to run schedules only from the database connection, and thus never picks up on any of the tasks sent to Redis, never running any schedules as a result:
https://github.com/ccarney16/pterodactyl-containers/blob/290ea14654a4cfb2d2bcf4f25e67cafc5f63c521/manifest/panel/root/entrypoint.sh#L110

Is there a reason why the entrypoint script points to a specific connection to run schedules off of? If not, I think it'd be easier to not point it to a specific connection so users can configure which connection they'd like to use for the queue accordingly (running the queue worker without any specific connection specified also appears to be how the [Pterodactyl documentation](https://pterodactyl.io/panel/1.0/getting_started.html) indicates this should be set up).

**Comment by ccarney16** [comment]
Thank you for showing this oversight, I did not know there were any changes in how the queues worked. Back in v0.7.x it was database. Ill be providing an update later today on all those changes

**Comment by ccarney16** [comment]
Updated container and pushed to repo.
