### ISSUE TITLE
On MacOS the deploy script cannot be executed

### ISSUE THREAD

**Issue by Kintull** [ccarney16/pterodactyl-containers#80]
When executing `./bin/deploy` script, the error is returned:

`sed: 1: ".env": invalid command code .`

While searching for a solution for this issue, I found this article:
https://rrikesh.com/troubleshooting/fixing-sed-error-undefined-label-and-invalid-command-code-on-macos/

It boils down to replacement of
`sed -i 's/hello/hola/' test.txt`
to
`sed -i '' 's/hola/hey/' test.txt`

That's because MacOS version of `sed` requires an extension where would be saved the file that is being changed in-place.

I am not sure what the right solution could be or if you want to look into it.

**Comment by Kintull** [comment]
There is also an issue with `yq` syntax.

I think I will just fix everything locally and close this issue.

**Comment by Razboy20** [comment]
For any future visitors here who need help with this problem, you can install the proper macos version of `yq@3` to replace `bin/yq` using `sudo wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_darwin_amd64 -O ./bin/yq`.
