### ISSUE TITLE
Howto upgrade existing 0.7 setup?

### ISSUE THREAD

**Issue by Syntax3rror404** [ccarney16/pterodactyl-containers#82]
I have running your 0.7 setup. How can I upgrade to the latest version? 
Can you please finish your wiki entry?

**Comment by ccarney16** [comment]
I have a rough outline listed here: https://github.com/ccarney16/pterodactyl-containers/issues/69

**Comment by Syntax3rror404** [comment]
The #69 dont help me :( when will step-by-step instructions be available?

**Comment by Syntax3rror404** [comment]
Now available in the wiki
