### ISSUE TITLE
Add more info to the wiki about standalone certs

### ISSUE THREAD

**Issue by haloflooder** [ccarney16/pterodactyl-containers#84]
Should include more info about getting a certificate without a webserver if they're only installing a daemon with an ssl cert on a server.

With the current information on the wiki, if you just run `docker-compose run --rm certbot certonly -d <domain>`. The container won't open the service ports and certbot would fail to get a certificate.

You would need to run `docker-compose run --rm --service-ports certbot certonly -d <domain>` in order to get a certificate successfully without a webserver.

**Comment by ccarney16** [comment]
Thank you for the heads up, that was an over sight I did not notice until now.
