### ISSUE TITLE
Getting node up and running

### ISSUE THREAD

**Issue by DesertCookie** [ccarney16/pterodactyl-containers#86]
I've got MariaDB and your container up and running in Unraid. I cannot, however, get a node running. All the tutorials SSH into a Linux system. `docker exec -it Pterodactyl bash` does not allow me to get access to a Linux terminal within the container. How do I get my node up and running?

Thanks.

**Comment by TekExplorer** [comment]
take a look at the [wiki](https://github.com/ccarney16/pterodactyl-containers/wiki) to learn how to set this up properly

**Comment by ccarney16** [comment]
Okay, If there is anything with Unraid, I do not support it. The template provided for unraid is very much out of date. Also these images are based on alpine linux, and do not contain bash. If your looking to execute a shell, you can use either ash or sh.
