### ISSUE TITLE
Rewrite panel updating page in wiki

### ISSUE THREAD

**Issue by Rake01** [ccarney16/pterodactyl-containers#88]
As a user myself, reading over the "Updating the panel" section in the wiki was quite inadequate, though it is mostly because I myself am not very proficient in the ways of Docker. I feel that the page needs to be rewritten a bit to accommodate to users like me, as I had to spend an hour or so looking around just to realize that I needed to pull the new image when attempting to update.
Here's a step by step:
Update panel image by doing `docker pull ccarney16/pterodactyl-panel:latest`
Stop panel, worker, and cron `docker-compose stop panel worker cron`
Start the panel `docker-compose up -d panel` which should update the panel to the latest version
Clear the template cache with `docker-compose exec panel php artisan view:clear` and `docker-compose exec panel php artisan config:clear`
Update the database with `docker-compose exec panel php artisan migrate --seed --force`
Start the worker and cron containers with `docker-compose up -d worker cron`

**Comment by ccarney16** [comment]
Actually with recent changes, it is no longer required to migrate/seed the database. and usually docker-compose up _should_ pull the images, but you are correct, I should have opted to use pull then bring up the project. Alongside with that, bringing down the containers beforehand is not required.

**Comment by jakehead20** [comment]
Cool! Makes updating a lot easier. Thanks for the info
