### ISSUE TITLE
unexpected stop of the container

### ISSUE THREAD

**Issue by vlotho** [ccarney16/pterodactyl-containers#97]
Hello,

I am trying to install the container with docker hub on a synology nas and the container does not start.
I have this error:
Pre-start: Waiting for database connection ...
Error: you need to provide a host and port to test.

I understand that we must be give the host and port settings, but where exactly?
Is this a base that must be created on the nas itself, or in the container? and how should it be created? with what data?

**Comment by ccarney16** [comment]
you can view the variables [here](https://github.com/ccarney16/pterodactyl-containers/blob/master/manifest/config/env/panel.env). The container uses the DB_HOST/DB_PORT variables to check if mysql is running or not. I plan on updating this in the future where pterodactyl.conf within /data can be used to assign variables.

**Comment by vlotho** [comment]
i have this error now :
```
Pre-start: Waiting for database connection...
Operation timed out
Operation timed out
Operation timed out
Operation timed out
Operation timed out
Pre-start: Database Connection Timeout (Is MySQL Running?)
```

the sql server is installed in the container?

**Comment by ccarney16** [comment]
No, the database is external. You would need to setup MariaDB.

**Comment by vlotho** [comment]
I do not really know ..
there i installed mariadb on my nas on port 3307, and it doesn't work either.
I created a database with the user and his password.
i created the variables in the container settings but it doesn't work either.

**Comment by ccarney16** [comment]
I need more information, unless its the same issue as the first post? You need to make sure the the database can be seen by the container. Check if you have a firewall in place that is blocking connections to mysql. I have not worked with synology, so I dont know what they do.

**Comment by vlotho** [comment]
the docker is on the same machine as the synology and I checked, port 3307 is open.
After that, the container doesn't start at all, so I don't even have access to a console to check the accesses, container side.

**Comment by ccarney16** [comment]
you should have access to logs to see what is going on... You do need to pass most of those variables Ive linked to above for the panel to function correctly, as those are passed directly to php.

**Comment by vlotho** [comment]
sorry i tried, live, on my nas, in ssh, but the nas is too compartmentalized. impossible to set up a docker without disrupting everything in the interface, or the functioning of the system, in general. suddenly, I have to go through the hub.
I have correctly configured all the variables in the hub interface but I still have the same error message.
I have my sql server which works with the same account / password.

**Comment by ccarney16** [comment]
I will have to assume that your setup has a problem. Docker logs the container output that can be viewed via `docker logs <container-id>`. `/storage/logs` (relative to the volume used by the container) is where application error logs are located. Your database needs to be visible from the container. If you have a firewall application enabled, it might be a good idea to check on that. Programs like firewalld add extra rules on top of what docker adds that can restrict inter container communications over multiple internal networks.
