### ISSUE TITLE
HTTP ERROR 500 after upgrade from 1.2.2 to 1.3.0

### ISSUE THREAD

**Issue by Syntax3rror404** [ccarney16/pterodactyl-containers#98]
After upgrading to the latest version, the containers start but only HTTP 500 Error is displayed

**Comment by Syntax3rror404** [comment]
Worker container log:

```
Pre-start: Waiting for database connection...

In Application.php line 690:
                                                                              
  Class 'Appstract\BladeDirectives\BladeDirectivesServiceProvider' not found  
```

**Comment by ccarney16** [comment]
Wipe /data/cache and restart the application.

**Comment by ratatouyee** [comment]
this solved the issue for me but seems to have caused the panel to become very slow

**Comment by Syntax3rror404** [comment]
Thanks @ccarney16 that worked for me. I dont have any performance issues with the ui.
